### ISSUE TITLE
Errors: functions not declared in this scope

### ISSUE THREAD

**Issue by davidedelvento** [davidmalcolm/gcc-python-plugin#112]
Compiling trunk (commit  257ad364a2d61d6289231ff65c3795656cf6dc27) with gcc v6.3.0 fails with 
```
gcc-location.c: In function ‘gcc_location gcc_location_get_caret(gcc_location)’:
gcc-location.c:68:65: error: ‘get_pure_location’ was not declared in this scope
   return gcc_private_make_location (get_pure_location (loc.inner));
                                                                 ^
gcc-location.c: In function ‘gcc_location gcc_location_get_start(gcc_location)’:
gcc-location.c:74:57: error: ‘get_start’ was not declared in this scope
   return gcc_private_make_location (get_start (loc.inner));
                                                         ^
gcc-location.c: In function ‘gcc_location gcc_location_get_finish(gcc_location)’:
gcc-location.c:80:58: error: ‘get_finish’ was not declared in this scope
   return gcc_private_make_location (get_finish (loc.inner));
```
Release v0.15 works fine (need to nose @afanfa)

**Comment by davidmalcolm** [comment]
These functions are declared in gcc's `input.h`, as of gcc 6 onwards, I *think*.  Is that file missing a `#include`, or does you `input.h` not have them, maybe?

**Comment by davidmalcolm** [comment]
Aha: looking at the gcc 6 branch, looks like input.h on that branch never got those functions:
https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=gcc/input.h;h=97c43332ee751d4187acf6fae4490eac2c4dbe7b;hb=4b5e15daff8b54440e3fda451c318ad31e532fab

Sorry about that.  The plugin's gcc-location.c needs to handle their absence.

**Comment by davidmalcolm** [comment]
Hopefully fixed by https://github.com/davidmalcolm/gcc-python-plugin/pull/114.

**Comment by davidmalcolm** [comment]
Should be fixed now.
