### ISSUE TITLE
Question: How can I get function declaration which is not in Callgraph?

### ISSUE THREAD

**Issue by aqjune** [davidmalcolm/gcc-python-plugin#151]
How can I get gcc.Function of a declared function which is not in Callgraph?

For example, in following code:
```
void g(int);
int f(int x, int y) {
  g(x + y);
}
```
`gcc.get_callgraph_nodes()` return f only, but not g.

Thanks

**Comment by davidmalcolm** [comment]
IIRC the gcc.Function represents the body of a function, and g's body isn't available: g was declared but was not defined.

You ought to be able to get at a gcc.FunctionDecl for the decl of g from the call statement.
