### ISSUE TITLE
0.17 build broken with GCC 8.3

### ISSUE THREAD

**Issue by doko42** [davidmalcolm/gcc-python-plugin#173]
One of you recent backports to GCC 8.3 broke the 0.17 build. The GCC version check needs to be adjusted.

--- gcc-python-plugin-0.17.orig/gcc-python-pretty-printer.c
+++ gcc-python-plugin-0.17/gcc-python-pretty-printer.c
@@ -46,8 +46,8 @@ PyGccPrettyPrinter_New(void)
        Use placement new to run it on obj->pp.  */
     new ((void*)&obj->pp)
         pretty_printer(
-# if (GCC_VERSION < 9000)
-                       /* GCC 9 eliminated the "prefix" param.  */
+# if (GCC_VERSION < 8003)
+                       /* GCC 8.3 eliminated the "prefix" param.  */
                        NULL,
 # endif
                        0);

**Comment by davidmalcolm** [comment]
Should be fixed by #175
