### ISSUE TITLE
Failed to get propper argument_types property on function declaration

### ISSUE THREAD

**Issue by bloff** [davidmalcolm/gcc-python-plugin#26]
The following declaration appears in the preprocessed stdio.h from gcc's standard C library:
    `extern int fscanf (FILE *__restrict __stream, const char *__restrict __format, ...);`

I made a python plugin for gcc with callbacks on PLUGIN_FINISH_DECL, hoping to translate such declarations into equivalent declarations in a different programming language.

However:
When parsing this declaration, I get a gcc.FunctionDecl object, and in this object there is a `type` attribute of type gcc.FunctionType, and the problem is: the `argument_types` attribute of this gcc.FunctionType is a list of length 1!

I expected length 3, with the last type being a va_args kind of thing...

I will try to fix it myself, but meanwhile I leave here an issue report.

**Comment by tromey** [comment]
See https://fedorahosted.org/gcc-python-plugin/ticket/61 for a patch
